// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IMessageFactory.proto

package com.yiyekeji.bean;

public final class IMessageFactory {
  private IMessageFactory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string senderId = 1;
    boolean hasSenderId();
    String getSenderId();
    
    // optional string receiverId = 2;
    boolean hasReceiverId();
    String getReceiverId();
    
    // optional string content = 3;
    boolean hasContent();
    String getContent();
    
    // optional string mainType = 4;
    boolean hasMainType();
    String getMainType();
    
    // optional string subType = 5;
    boolean hasSubType();
    String getSubType();
    
    // repeated .IMessage.User user = 6;
    java.util.List<com.yiyekeji.bean.IMessageFactory.IMessage.User> 
        getUserList();
    com.yiyekeji.bean.IMessageFactory.IMessage.User getUser(int index);
    int getUserCount();
    java.util.List<? extends com.yiyekeji.bean.IMessageFactory.IMessage.UserOrBuilder> 
        getUserOrBuilderList();
    com.yiyekeji.bean.IMessageFactory.IMessage.UserOrBuilder getUserOrBuilder(
        int index);
    
    // optional string result = 7;
    boolean hasResult();
    String getResult();
  }
  public static final class IMessage extends
      com.google.protobuf.GeneratedMessage
      implements IMessageOrBuilder {
    // Use IMessage.newBuilder() to construct.
    private IMessage(Builder builder) {
      super(builder);
    }
    private IMessage(boolean noInit) {}
    
    private static final IMessage defaultInstance;
    public static IMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public IMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yiyekeji.bean.IMessageFactory.internal_static_IMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yiyekeji.bean.IMessageFactory.internal_static_IMessage_fieldAccessorTable;
    }
    
    public interface UserOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string username = 1;
      boolean hasUsername();
      String getUsername();
      
      // required string password = 2;
      boolean hasPassword();
      String getPassword();
    }
    public static final class User extends
        com.google.protobuf.GeneratedMessage
        implements UserOrBuilder {
      // Use User.newBuilder() to construct.
      private User(Builder builder) {
        super(builder);
      }
      private User(boolean noInit) {}
      
      private static final User defaultInstance;
      public static User getDefaultInstance() {
        return defaultInstance;
      }
      
      public User getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yiyekeji.bean.IMessageFactory.internal_static_IMessage_User_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yiyekeji.bean.IMessageFactory.internal_static_IMessage_User_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string username = 1;
      public static final int USERNAME_FIELD_NUMBER = 1;
      private java.lang.Object username_;
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUsername() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            username_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string password = 2;
      public static final int PASSWORD_FIELD_NUMBER = 2;
      private java.lang.Object password_;
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPassword() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            password_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        username_ = "";
        password_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasUsername()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPassword()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getUsernameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getPasswordBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getUsernameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getPasswordBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.yiyekeji.bean.IMessageFactory.IMessage.User parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.yiyekeji.bean.IMessageFactory.IMessage.User parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.yiyekeji.bean.IMessageFactory.IMessage.User parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.yiyekeji.bean.IMessageFactory.IMessage.User parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.yiyekeji.bean.IMessageFactory.IMessage.User parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.yiyekeji.bean.IMessageFactory.IMessage.User parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.yiyekeji.bean.IMessageFactory.IMessage.User parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.yiyekeji.bean.IMessageFactory.IMessage.User parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.yiyekeji.bean.IMessageFactory.IMessage.User parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.yiyekeji.bean.IMessageFactory.IMessage.User parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.yiyekeji.bean.IMessageFactory.IMessage.User prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.yiyekeji.bean.IMessageFactory.IMessage.UserOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.yiyekeji.bean.IMessageFactory.internal_static_IMessage_User_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.yiyekeji.bean.IMessageFactory.internal_static_IMessage_User_fieldAccessorTable;
        }
        
        // Construct using com.yiyekeji.bean.IMessageFactory.IMessage.User.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          username_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          password_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.yiyekeji.bean.IMessageFactory.IMessage.User.getDescriptor();
        }
        
        public com.yiyekeji.bean.IMessageFactory.IMessage.User getDefaultInstanceForType() {
          return com.yiyekeji.bean.IMessageFactory.IMessage.User.getDefaultInstance();
        }
        
        public com.yiyekeji.bean.IMessageFactory.IMessage.User build() {
          com.yiyekeji.bean.IMessageFactory.IMessage.User result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.yiyekeji.bean.IMessageFactory.IMessage.User buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.yiyekeji.bean.IMessageFactory.IMessage.User result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.yiyekeji.bean.IMessageFactory.IMessage.User buildPartial() {
          com.yiyekeji.bean.IMessageFactory.IMessage.User result = new com.yiyekeji.bean.IMessageFactory.IMessage.User(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.username_ = username_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.password_ = password_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.yiyekeji.bean.IMessageFactory.IMessage.User) {
            return mergeFrom((com.yiyekeji.bean.IMessageFactory.IMessage.User)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.yiyekeji.bean.IMessageFactory.IMessage.User other) {
          if (other == com.yiyekeji.bean.IMessageFactory.IMessage.User.getDefaultInstance()) return this;
          if (other.hasUsername()) {
            setUsername(other.getUsername());
          }
          if (other.hasPassword()) {
            setPassword(other.getPassword());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasUsername()) {
            
            return false;
          }
          if (!hasPassword()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                username_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                password_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string username = 1;
        private java.lang.Object username_ = "";
        public boolean hasUsername() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getUsername() {
          java.lang.Object ref = username_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            username_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setUsername(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          username_ = value;
          onChanged();
          return this;
        }
        public Builder clearUsername() {
          bitField0_ = (bitField0_ & ~0x00000001);
          username_ = getDefaultInstance().getUsername();
          onChanged();
          return this;
        }
        void setUsername(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          username_ = value;
          onChanged();
        }
        
        // required string password = 2;
        private java.lang.Object password_ = "";
        public boolean hasPassword() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getPassword() {
          java.lang.Object ref = password_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            password_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setPassword(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          password_ = value;
          onChanged();
          return this;
        }
        public Builder clearPassword() {
          bitField0_ = (bitField0_ & ~0x00000002);
          password_ = getDefaultInstance().getPassword();
          onChanged();
          return this;
        }
        void setPassword(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          password_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:IMessage.User)
      }
      
      static {
        defaultInstance = new User(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:IMessage.User)
    }
    
    private int bitField0_;
    // optional string senderId = 1;
    public static final int SENDERID_FIELD_NUMBER = 1;
    private java.lang.Object senderId_;
    public boolean hasSenderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSenderId() {
      java.lang.Object ref = senderId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          senderId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string receiverId = 2;
    public static final int RECEIVERID_FIELD_NUMBER = 2;
    private java.lang.Object receiverId_;
    public boolean hasReceiverId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getReceiverId() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          receiverId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReceiverIdBytes() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        receiverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string content = 3;
    public static final int CONTENT_FIELD_NUMBER = 3;
    private java.lang.Object content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          content_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string mainType = 4;
    public static final int MAINTYPE_FIELD_NUMBER = 4;
    private java.lang.Object mainType_;
    public boolean hasMainType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getMainType() {
      java.lang.Object ref = mainType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mainType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMainTypeBytes() {
      java.lang.Object ref = mainType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mainType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string subType = 5;
    public static final int SUBTYPE_FIELD_NUMBER = 5;
    private java.lang.Object subType_;
    public boolean hasSubType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getSubType() {
      java.lang.Object ref = subType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          subType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSubTypeBytes() {
      java.lang.Object ref = subType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        subType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .IMessage.User user = 6;
    public static final int USER_FIELD_NUMBER = 6;
    private java.util.List<com.yiyekeji.bean.IMessageFactory.IMessage.User> user_;
    public java.util.List<com.yiyekeji.bean.IMessageFactory.IMessage.User> getUserList() {
      return user_;
    }
    public java.util.List<? extends com.yiyekeji.bean.IMessageFactory.IMessage.UserOrBuilder> 
        getUserOrBuilderList() {
      return user_;
    }
    public int getUserCount() {
      return user_.size();
    }
    public com.yiyekeji.bean.IMessageFactory.IMessage.User getUser(int index) {
      return user_.get(index);
    }
    public com.yiyekeji.bean.IMessageFactory.IMessage.UserOrBuilder getUserOrBuilder(
        int index) {
      return user_.get(index);
    }
    
    // optional string result = 7;
    public static final int RESULT_FIELD_NUMBER = 7;
    private java.lang.Object result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          result_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      senderId_ = "";
      receiverId_ = "";
      content_ = "";
      mainType_ = "";
      subType_ = "";
      user_ = java.util.Collections.emptyList();
      result_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getUserCount(); i++) {
        if (!getUser(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSenderIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getReceiverIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getContentBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMainTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSubTypeBytes());
      }
      for (int i = 0; i < user_.size(); i++) {
        output.writeMessage(6, user_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(7, getResultBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSenderIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getReceiverIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getContentBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMainTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSubTypeBytes());
      }
      for (int i = 0; i < user_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, user_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getResultBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yiyekeji.bean.IMessageFactory.IMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yiyekeji.bean.IMessageFactory.IMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yiyekeji.bean.IMessageFactory.IMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yiyekeji.bean.IMessageFactory.IMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yiyekeji.bean.IMessageFactory.IMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yiyekeji.bean.IMessageFactory.IMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yiyekeji.bean.IMessageFactory.IMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yiyekeji.bean.IMessageFactory.IMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yiyekeji.bean.IMessageFactory.IMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yiyekeji.bean.IMessageFactory.IMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yiyekeji.bean.IMessageFactory.IMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.yiyekeji.bean.IMessageFactory.IMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yiyekeji.bean.IMessageFactory.internal_static_IMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yiyekeji.bean.IMessageFactory.internal_static_IMessage_fieldAccessorTable;
      }
      
      // Construct using com.yiyekeji.bean.IMessageFactory.IMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        senderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        receiverId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        mainType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        subType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          userBuilder_.clear();
        }
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yiyekeji.bean.IMessageFactory.IMessage.getDescriptor();
      }
      
      public com.yiyekeji.bean.IMessageFactory.IMessage getDefaultInstanceForType() {
        return com.yiyekeji.bean.IMessageFactory.IMessage.getDefaultInstance();
      }
      
      public com.yiyekeji.bean.IMessageFactory.IMessage build() {
        com.yiyekeji.bean.IMessageFactory.IMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yiyekeji.bean.IMessageFactory.IMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yiyekeji.bean.IMessageFactory.IMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yiyekeji.bean.IMessageFactory.IMessage buildPartial() {
        com.yiyekeji.bean.IMessageFactory.IMessage result = new com.yiyekeji.bean.IMessageFactory.IMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.senderId_ = senderId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.receiverId_ = receiverId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mainType_ = mainType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.subType_ = subType_;
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            user_ = java.util.Collections.unmodifiableList(user_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yiyekeji.bean.IMessageFactory.IMessage) {
          return mergeFrom((com.yiyekeji.bean.IMessageFactory.IMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.yiyekeji.bean.IMessageFactory.IMessage other) {
        if (other == com.yiyekeji.bean.IMessageFactory.IMessage.getDefaultInstance()) return this;
        if (other.hasSenderId()) {
          setSenderId(other.getSenderId());
        }
        if (other.hasReceiverId()) {
          setReceiverId(other.getReceiverId());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasMainType()) {
          setMainType(other.getMainType());
        }
        if (other.hasSubType()) {
          setSubType(other.getSubType());
        }
        if (userBuilder_ == null) {
          if (!other.user_.isEmpty()) {
            if (user_.isEmpty()) {
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureUserIsMutable();
              user_.addAll(other.user_);
            }
            onChanged();
          }
        } else {
          if (!other.user_.isEmpty()) {
            if (userBuilder_.isEmpty()) {
              userBuilder_.dispose();
              userBuilder_ = null;
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000020);
              userBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUserFieldBuilder() : null;
            } else {
              userBuilder_.addAllMessages(other.user_);
            }
          }
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getUserCount(); i++) {
          if (!getUser(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              senderId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              receiverId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              content_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              mainType_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              subType_ = input.readBytes();
              break;
            }
            case 50: {
              com.yiyekeji.bean.IMessageFactory.IMessage.User.Builder subBuilder = com.yiyekeji.bean.IMessageFactory.IMessage.User.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addUser(subBuilder.buildPartial());
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              result_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string senderId = 1;
      private java.lang.Object senderId_ = "";
      public boolean hasSenderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSenderId() {
        java.lang.Object ref = senderId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          senderId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSenderId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        senderId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSenderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        senderId_ = getDefaultInstance().getSenderId();
        onChanged();
        return this;
      }
      void setSenderId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        senderId_ = value;
        onChanged();
      }
      
      // optional string receiverId = 2;
      private java.lang.Object receiverId_ = "";
      public boolean hasReceiverId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getReceiverId() {
        java.lang.Object ref = receiverId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          receiverId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReceiverId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        receiverId_ = value;
        onChanged();
        return this;
      }
      public Builder clearReceiverId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        receiverId_ = getDefaultInstance().getReceiverId();
        onChanged();
        return this;
      }
      void setReceiverId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        receiverId_ = value;
        onChanged();
      }
      
      // optional string content = 3;
      private java.lang.Object content_ = "";
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      void setContent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
      }
      
      // optional string mainType = 4;
      private java.lang.Object mainType_ = "";
      public boolean hasMainType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getMainType() {
        java.lang.Object ref = mainType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mainType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMainType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mainType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMainType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mainType_ = getDefaultInstance().getMainType();
        onChanged();
        return this;
      }
      void setMainType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        mainType_ = value;
        onChanged();
      }
      
      // optional string subType = 5;
      private java.lang.Object subType_ = "";
      public boolean hasSubType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getSubType() {
        java.lang.Object ref = subType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          subType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSubType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        subType_ = value;
        onChanged();
        return this;
      }
      public Builder clearSubType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        subType_ = getDefaultInstance().getSubType();
        onChanged();
        return this;
      }
      void setSubType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        subType_ = value;
        onChanged();
      }
      
      // repeated .IMessage.User user = 6;
      private java.util.List<com.yiyekeji.bean.IMessageFactory.IMessage.User> user_ =
        java.util.Collections.emptyList();
      private void ensureUserIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          user_ = new java.util.ArrayList<com.yiyekeji.bean.IMessageFactory.IMessage.User>(user_);
          bitField0_ |= 0x00000020;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.yiyekeji.bean.IMessageFactory.IMessage.User, com.yiyekeji.bean.IMessageFactory.IMessage.User.Builder, com.yiyekeji.bean.IMessageFactory.IMessage.UserOrBuilder> userBuilder_;
      
      public java.util.List<com.yiyekeji.bean.IMessageFactory.IMessage.User> getUserList() {
        if (userBuilder_ == null) {
          return java.util.Collections.unmodifiableList(user_);
        } else {
          return userBuilder_.getMessageList();
        }
      }
      public int getUserCount() {
        if (userBuilder_ == null) {
          return user_.size();
        } else {
          return userBuilder_.getCount();
        }
      }
      public com.yiyekeji.bean.IMessageFactory.IMessage.User getUser(int index) {
        if (userBuilder_ == null) {
          return user_.get(index);
        } else {
          return userBuilder_.getMessage(index);
        }
      }
      public Builder setUser(
          int index, com.yiyekeji.bean.IMessageFactory.IMessage.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.set(index, value);
          onChanged();
        } else {
          userBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setUser(
          int index, com.yiyekeji.bean.IMessageFactory.IMessage.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.set(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addUser(com.yiyekeji.bean.IMessageFactory.IMessage.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(value);
          onChanged();
        } else {
          userBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addUser(
          int index, com.yiyekeji.bean.IMessageFactory.IMessage.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(index, value);
          onChanged();
        } else {
          userBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addUser(
          com.yiyekeji.bean.IMessageFactory.IMessage.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addUser(
          int index, com.yiyekeji.bean.IMessageFactory.IMessage.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllUser(
          java.lang.Iterable<? extends com.yiyekeji.bean.IMessageFactory.IMessage.User> values) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          super.addAll(values, user_);
          onChanged();
        } else {
          userBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          userBuilder_.clear();
        }
        return this;
      }
      public Builder removeUser(int index) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.remove(index);
          onChanged();
        } else {
          userBuilder_.remove(index);
        }
        return this;
      }
      public com.yiyekeji.bean.IMessageFactory.IMessage.User.Builder getUserBuilder(
          int index) {
        return getUserFieldBuilder().getBuilder(index);
      }
      public com.yiyekeji.bean.IMessageFactory.IMessage.UserOrBuilder getUserOrBuilder(
          int index) {
        if (userBuilder_ == null) {
          return user_.get(index);  } else {
          return userBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.yiyekeji.bean.IMessageFactory.IMessage.UserOrBuilder> 
           getUserOrBuilderList() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(user_);
        }
      }
      public com.yiyekeji.bean.IMessageFactory.IMessage.User.Builder addUserBuilder() {
        return getUserFieldBuilder().addBuilder(
            com.yiyekeji.bean.IMessageFactory.IMessage.User.getDefaultInstance());
      }
      public com.yiyekeji.bean.IMessageFactory.IMessage.User.Builder addUserBuilder(
          int index) {
        return getUserFieldBuilder().addBuilder(
            index, com.yiyekeji.bean.IMessageFactory.IMessage.User.getDefaultInstance());
      }
      public java.util.List<com.yiyekeji.bean.IMessageFactory.IMessage.User.Builder> 
           getUserBuilderList() {
        return getUserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.yiyekeji.bean.IMessageFactory.IMessage.User, com.yiyekeji.bean.IMessageFactory.IMessage.User.Builder, com.yiyekeji.bean.IMessageFactory.IMessage.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.yiyekeji.bean.IMessageFactory.IMessage.User, com.yiyekeji.bean.IMessageFactory.IMessage.User.Builder, com.yiyekeji.bean.IMessageFactory.IMessage.UserOrBuilder>(
                  user_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      
      // optional string result = 7;
      private java.lang.Object result_ = "";
      public boolean hasResult() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setResult(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000040);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      void setResult(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        result_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:IMessage)
    }
    
    static {
      defaultInstance = new IMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:IMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_IMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_IMessage_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IMessage_User_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025IMessageFactory.proto\"\276\001\n\010IMessage\022\020\n\010" +
      "senderId\030\001 \001(\t\022\022\n\nreceiverId\030\002 \001(\t\022\017\n\007co" +
      "ntent\030\003 \001(\t\022\020\n\010mainType\030\004 \001(\t\022\017\n\007subType" +
      "\030\005 \001(\t\022\034\n\004user\030\006 \003(\0132\016.IMessage.User\022\016\n\006" +
      "result\030\007 \001(\t\032*\n\004User\022\020\n\010username\030\001 \002(\t\022\020" +
      "\n\010password\030\002 \002(\tB$\n\021com.yiyekeji.beanB\017I" +
      "MessageFactory"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_IMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_IMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_IMessage_descriptor,
              new java.lang.String[] { "SenderId", "ReceiverId", "Content", "MainType", "SubType", "User", "Result", },
              com.yiyekeji.bean.IMessageFactory.IMessage.class,
              com.yiyekeji.bean.IMessageFactory.IMessage.Builder.class);
          internal_static_IMessage_User_descriptor =
            internal_static_IMessage_descriptor.getNestedTypes().get(0);
          internal_static_IMessage_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_IMessage_User_descriptor,
              new java.lang.String[] { "Username", "Password", },
              com.yiyekeji.bean.IMessageFactory.IMessage.User.class,
              com.yiyekeji.bean.IMessageFactory.IMessage.User.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
